---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	intake_subgraph(intake_subgraph)
	ask_research_consent(ask_research_consent)
	parse_research_consent(parse_research_consent)
	market_subgraph(market_subgraph)
	ask_gains_consent(ask_gains_consent)
	parse_gains_consent(parse_gains_consent)
	gains_subgraph(gains_subgraph)
	show_plan_and_ask_payment_consent(show_plan_and_ask_payment_consent)
	parse_payment_consent(parse_payment_consent)
	payment_subgraph(payment_subgraph)
	conclusion_node(conclusion_node)
	__end__([<p>__end__</p>]):::last
	__start__ --> intake_subgraph;
	ask_gains_consent --> parse_gains_consent;
	ask_research_consent --> parse_research_consent;
	gains_subgraph --> show_plan_and_ask_payment_consent;
	intake_subgraph --> ask_research_consent;
	market_subgraph --> ask_gains_consent;
	parse_gains_consent -.-> __end__;
	parse_gains_consent -.-> gains_subgraph;
	parse_payment_consent -.-> conclusion_node;
	parse_payment_consent -.-> payment_subgraph;
	parse_research_consent -.-> __end__;
	parse_research_consent -.-> market_subgraph;
	payment_subgraph --> conclusion_node;
	show_plan_and_ask_payment_consent --> parse_payment_consent;
	conclusion_node --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
