---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	ask_research_consent(ask_research_consent)
	parse_research_consent(parse_research_consent)
	ask_gains_consent(ask_gains_consent)
	parse_gains_consent(parse_gains_consent)
	show_gains(show_gains)
	ask_execute_consent(ask_execute_consent)
	parse_execute_consent(parse_execute_consent)
	__end__([<p>__end__</p>]):::last
	__start__ --> intake_subgraph\3a__start__;
	ask_execute_consent --> parse_execute_consent;
	ask_gains_consent --> parse_gains_consent;
	ask_research_consent --> parse_research_consent;
	gains_subgraph\3a__end__ --> show_gains;
	intake_subgraph\3a__end__ --> ask_research_consent;
	market_subgraph\3astore_research --> ask_gains_consent;
	parse_execute_consent -.-> __end__;
	parse_execute_consent -.-> payment_subgraph\3ainitiate_payment;
	parse_gains_consent -.-> __end__;
	parse_gains_consent -.-> gains_subgraph\3a__start__;
	parse_research_consent -.-> __end__;
	parse_research_consent -.-> market_subgraph\3a__start__;
	show_gains --> ask_execute_consent;
	payment_subgraph\3averify_payment --> __end__;
	subgraph intake_subgraph
	intake_subgraph\3a__start__(<p>__start__</p>)
	intake_subgraph\3aintake(intake)
	intake_subgraph\3a__end__(<p>__end__</p>)
	intake_subgraph\3a__start__ --> intake_subgraph\3aintake;
	intake_subgraph\3aintake -. &nbsp;done&nbsp; .-> intake_subgraph\3a__end__;
	intake_subgraph\3aintake -. &nbsp;continue&nbsp; .-> intake_subgraph\3aintake;
	end
	subgraph market_subgraph
	market_subgraph\3a__start__(<p>__start__</p>)
	market_subgraph\3aresearcher(researcher)
	market_subgraph\3atools(tools)
	market_subgraph\3astore_research(store_research)
	market_subgraph\3a__start__ --> market_subgraph\3aresearcher;
	market_subgraph\3aresearcher -. &nbsp;__end__&nbsp; .-> market_subgraph\3astore_research;
	market_subgraph\3aresearcher -.-> market_subgraph\3atools;
	market_subgraph\3atools --> market_subgraph\3aresearcher;
	end
	subgraph gains_subgraph
	gains_subgraph\3a__start__(<p>__start__</p>)
	gains_subgraph\3agains_planner(gains_planner)
	gains_subgraph\3atools(tools)
	gains_subgraph\3a__end__(<p>__end__</p>)
	gains_subgraph\3a__start__ --> gains_subgraph\3agains_planner;
	gains_subgraph\3agains_planner -.-> gains_subgraph\3a__end__;
	gains_subgraph\3agains_planner -.-> gains_subgraph\3atools;
	gains_subgraph\3atools --> gains_subgraph\3agains_planner;
	end
	subgraph payment_subgraph
	payment_subgraph\3ainitiate_payment(initiate_payment)
	payment_subgraph\3averify_payment(verify_payment)
	payment_subgraph\3ainitiate_payment --> payment_subgraph\3averify_payment;
	end
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
